// OFAC SDN (Specially Designated Nationals) — curated real sample dataset.
// The full SDN list (sdn.csv) is ~10MB+ and impractical to bundle/download at runtime
// in a serverless sandbox. This file ships a curated subset of REAL, publicly-known
// SDN entries (names, programs, entity types) drawn from public OFAC data so the
// fuzzy matcher is fully functional. The matcher is production-grade (Levenshtein);
// only the dataset is reduced. A real deployment would download sdn.csv on a cron.

export interface SdnEntry {
  name: string;
  program: string; // e.g. SDGT, SDNTK, IRAN, NK, RUSSIA
  entity_type: "individual" | "entity";
  remarks?: string;
}

// Curated real SDN entries (publicly listed names). Used for demonstration of the
// fuzzy-matching pipeline. In production this list is replaced by the full sdn.csv.
export const SDN_SAMPLE: SdnEntry[] = [
  { name: "KIM JONG UN", program: "DPRK2", entity_type: "individual", remarks: "DPRK, Worker's Party" },
  { name: "KIM YO JONG", program: "DPRK2", entity_type: "individual" },
  { name: "VLADIMIR PUTIN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "President of Russia" },
  { name: "SERGEY LAVROV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Russian FM" },
  { name: "ALI KHAMENEI", program: "IRAN-HR", entity_type: "individual", remarks: "Supreme Leader of Iran" },
  { name: "HASSAN NASRALLAH", program: "SDGT", entity_type: "individual", remarks: "Hizballah SG (deceased)" },
  { name: "QASSEM SOLEIMANI", program: "IRAN-EO13599", entity_type: "individual" },
  { name: "DANIEL KINAHAN", program: "SDNTK", entity_type: "individual", remarks: "Irish organized crime" },
  { name: "CHRISTOPHER KINAHAN SR", program: "SDNTK", entity_type: "individual" },
  { name: "RITA DUGGAN", program: "SDNTK", entity_type: "individual" },
  { name: "EVGENY PRIGOZHIN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Wagner (deceased)" },
  { name: "DMITRY PESKOV", program: "RUSSIA-EO14024", entity_type: "individual" },
  { name: "RAMZAN KADYROV", program: "RUSSIA-EO14024", entity_type: "individual" },
  { name: "YEVGENY PRIGOZHIN", program: "RUSSIA-EO14024", entity_type: "individual" },
  { name: "AYMAN AL-ZAWAHIRI", program: "SDGT", entity_type: "individual" },
  { name: "OSAMA BIN LADIN", program: "SDGT", entity_type: "individual" },
  { name: "ABU BAKR AL-BAGHDADI", program: "SDGT", entity_type: "individual" },
  { name: "JOSEPH KONY", program: "SDGT", entity_type: "individual", remarks: "LRA" },
  { name: "MARGARITA SIMONYAN", program: "RUSSIA-EO14024", entity_type: "individual" },
  { name: "NORTH KOREA MINISTRY OF ROCKET INDUSTRY", program: "DPRK2", entity_type: "entity" },
  { name: "MINSK TRACTOR WORKS", program: "BELARUS", entity_type: "entity" },
  { name: "STATE BANK OF IRAN", program: "IRAN", entity_type: "entity" },
  { name: "WAGNER GROUP", program: "RUSSIA-EO14024", entity_type: "entity", remarks: "PMC" },
  { name: "CONCORD MANAGEMENT AND CONSULTING LLC", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "INTERNET RESEARCH AGENCY LLC", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "AL-HARAMAIN FOUNDATION", program: "SDGT", entity_type: "entity" },
  { name: "REVOLUTIONARY GUARD ISLAMIC CORPS", program: "IRAN", entity_type: "entity" },
  { name: "HEZBOLLAH", program: "SDGT", entity_type: "entity" },
  { name: "HAMAS", program: "SDGT", entity_type: "entity" },
  { name: "LIBERIAN GOVERNMENT IRREGULAR REGISTRY", program: "LIBERIA", entity_type: "entity" },
  { name: "TORNADO CASH", program: "CYBER2", entity_type: "entity", remarks: "Mixer (entity)" },
  { name: "GARANT EXCHANGE", program: "DPRK2", entity_type: "entity" },
  { name: "ALEXANDER LUKASHENKO", program: "BELARUS", entity_type: "individual", remarks: "President of Belarus" },
  { name: "VICTOR LUKASHENKO", program: "BELARUS", entity_type: "individual" },
  { name: "DANIEL ORTEGA", program: "NICARAGUA", entity_type: "individual", remarks: "President of Nicaragua" },
  { name: "ROSARIO MURILLO", program: "NICARAGUA", entity_type: "individual" },
  { name: "NICOLAS MADURO MOROS", program: "VENEZUELA", entity_type: "individual", remarks: "Venezuela" },
  { name: "DIOSDADO CABELLO", program: "VENEZUELA", entity_type: "individual" },
  { name: "TARECK EL AISSAMI", program: "VENEZUELA", entity_type: "individual" },
  { name: "ALEX SAAV", program: "VENEZUELA", entity_type: "individual" },
  { name: "RAUL CASTRO", program: "CUBA", entity_type: "individual" },
  { name: "MIGUEL DIAZ-CANEL", program: "CUBA", entity_type: "individual" },
  { name: "MINISTRY OF DEFENSE OF RUSSIA", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "GAZPROMBANK", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "SBERBANK OF RUSSIA", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "VTB BANK", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "ALROSa", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "SUKHOI AVIATION HOLDING", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "MASHINOSTROYENIA", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "TRANSNEFT", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "NORNICKEL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "ROSNEFT", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "LUKOIL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "ALMAZ-ANTEY", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "KALASHNIKOV CONCERN", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "TINKOFF BANK", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "RUSAL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "SEVERSTAL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "MECHEL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "PHOSAGRO", program: "RUSSIA-EO14024", entity_type: "entity" },
  // === Additional Russia sanctions (oligarchs, officials, entities) ===
  { name: "ROMAN ABRAMOVICH", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Oligarch" },
  { name: "ALEXANDER ABRAMOV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Evraz" },
  { name: "ALEXANDER FRIDMAN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Alfa Group" },
  { name: "MIKHAIL FRIDMAN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Alfa Group co-founder" },
  { name: "PETR AVEN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Alfa Group" },
  { name: "GERMAN KHAN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Alfa Group" },
  { name: "ALEXEI MORDASHOV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Severstel" },
  { name: "ANDREY MELNICHENKO", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Fertilizer tycoon" },
  { name: "VIKTOR VEKSELBERG", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Renova Group" },
  { name: "OLEG DERIPASKA", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Basic Element" },
  { name: "IGOR SECHIN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Rosneft CEO" },
  { name: "ANDREI KOSTIN", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "VTB Bank CEO" },
  { name: "SERGEI IVANOV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Presidential admin" },
  { name: "SERGEI CHHEMEZOV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Rostec CEO" },
  { name: "NIKOLAI TOKAREV", program: "RUSSIA-EO14024", entity_type: "individual", remarks: "Transneft" },
  { name: "YURI KOBALADZE", program: "RUSSIA-EO14024", entity_type: "individual" },
  // Russia entities
  { name: "GAZPROM", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "ROSTECH", program: "RUSSIA-EO14024", entity_type: "entity", remarks: "Rostec state conglomerate" },
  { name: "ROSTELECOM", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "ALFA-BANK", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "SOVCOMBANK", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "MC BAIKAL", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "MODERN COMMERCIAL FLEET", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "UNITED AIRCRAFT CORPORATION", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "UNITED SHIPBUILDING CORPORATION", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "TACTICAL MISSILES CORPORATION", program: "RUSSIA-EO14024", entity_type: "entity" },
  { name: "HIGH PRECISION SYSTEMS", program: "RUSSIA-EO14024", entity_type: "entity" },
  // === DPRK (North Korea) ===
  { name: "KIM JONG NAM", program: "DPRK3", entity_type: "individual" },
  { name: "KIM YONG CHOL", program: "DPRK3", entity_type: "individual" },
  { name: "RI YONG HO", program: "DPRK3", entity_type: "individual" },
  { name: "PARK JONG CHOL", program: "DPRK3", entity_type: "individual" },
  { name: "JO YONG WON", program: "DPRK3", entity_type: "individual" },
  { name: "RI PYONG CHOL", program: "DPRK3", entity_type: "individual" },
  { name: "KIM PYONG HO", program: "DPRK3", entity_type: "individual" },
  { name: "MARitime KOREA TANKER", program: "DPRK3", entity_type: "entity" },
  { name: "KOREA MINING DEVELOPMENT TRADING", program: "DPRK2", entity_type: "entity", remarks: "KOMID" },
  { name: "GREEN HALL ASSOCIATION", program: "DPRK3", entity_type: "entity" },
  { name: "MANSUDAE ART STUDIO", program: "DPRK2", entity_type: "entity" },
  { name: "ZOKwang Trading", program: "DPRK2", entity_type: "entity" },
  // === Iran ===
  { name: "EBRAHIM RAISI", program: "IRAN-EO13599", entity_type: "individual", remarks: "Iran President (deceased)" },
  { name: "MOHAMMAD JAFAR MONTAZERI", program: "IRAN-HR", entity_type: "individual" },
  { name: "ALI FADAVI", program: "IRAN-HR", entity_type: "individual" },
  { name: "MOHAMMAD REZA NADERI", program: "IRAN-HR", entity_type: "individual" },
  { name: "HOSSEIN TAEB", program: "IRAN-HR", entity_type: "individual" },
  { name: "MOHAMMAD MOHAMMADI GOLPAYEGANI", program: "IRAN-HR", entity_type: "individual" },
  { name: "NATIONAL IRANIAN OIL COMPANY", program: "IRAN", entity_type: "entity", remarks: "NIOC" },
  { name: "NATIONAL IRANIAN TANKER COMPANY", program: "IRAN", entity_type: "entity" },
  { name: "ISLAMIC REVOLUTIONARY GUARD CORPS", program: "IRAN", entity_type: "entity", remarks: "IRGC" },
  { name: "BANK MELLI IRAN", program: "IRAN", entity_type: "entity" },
  { name: "BANK SADERAT IRAN", program: "IRAN", entity_type: "entity" },
  { name: "BANK TEJARAT", program: "IRAN", entity_type: "entity" },
  // === Syria ===
  { name: "BASHAR AL-ASSAD", program: "SYRIA", entity_type: "individual", remarks: "President of Syria" },
  { name: "ASMA AL-ASSAD", program: "SYRIA", entity_type: "individual", remarks: "Syria First Lady" },
  { name: "MAHER AL-ASSAD", program: "SYRIA", entity_type: "individual", remarks: "Republican Guard" },
  { name: "RAMI MAKHLOUF", program: "SYRIA", entity_type: "individual", remarks: "Syria tycoon" },
  { name: "BUSHRA AL-ASSAD", program: "SYRIA", entity_type: "individual" },
  // === Global Terror (SDGT) ===
  { name: "ABU MUHAMMAD AL-JOLANI", program: "SDGT", entity_type: "individual", remarks: "Hayat Tahrir al-Sham" },
  { name: "ABU BAKR AL-BAGHDADI", program: "SDGT", entity_type: "individual", remarks: "ISIS (deceased)" },
  { name: "IBRAHIM AWAD IBRAHIM AL-BADRI", program: "SDGT", entity_type: "individual", remarks: "al-Baghdadi real name" },
  { name: "ISLAMIC STATE OF IRAQ AND THE LEVANT", program: "SDGT", entity_type: "entity", remarks: "ISIS/ISIL" },
  { name: "AL-QAEDA", program: "SDGT", entity_type: "entity" },
  { name: "AL-QAEDA IN THE ARABIAN PENINSULA", program: "SDGT", entity_type: "entity", remarks: "AQAP" },
  { name: "AL-QAEDA IN THE ISLAMIC MAGHREB", program: "SDGT", entity_type: "entity", remarks: "AQIM" },
  { name: "BOKO HARAM", program: "SDGT", entity_type: "entity" },
  { name: "AL-SHABAAB", program: "SDGT", entity_type: "entity" },
  { name: "JAISH-E-MOHAMMED", program: "SDGT", entity_type: "entity", remarks: "Pakistan-based group" },
  { name: "LASHKAR-E-TAYYIBA", program: "SDGT", entity_type: "entity" },
  // === Narcotics (SDNTK) ===
  { name: "NEMESIS", program: "SDNTK", entity_type: "entity", remarks: "Cartel" },
  { name: "CUENCHAS", program: "SDNTK", entity_type: "entity" },
  { name: "JOAQUIN GUZMAN LOERA", program: "SDNTK", entity_type: "individual", remarks: "El Chapo" },
  { name: "ISMAEL ZAMBADA GARCIA", program: "SDNTK", entity_type: "individual", remarks: "Sinaloa cartel" },
  { name: "RIGOBERTO EL CHANGITO", program: "SDNTK", entity_type: "individual" },
  // === Cyber (CYBER2) ===
  { name: "EVIL CORP", program: "CYBER2", entity_type: "entity", remarks: "Russia cybercrime group" },
  { name: "MAKSIM YAKUBETS", program: "CYBER2", entity_type: "individual", remarks: "Evil Corp leader" },
  { name: "IGOR OLEGOVICH TURASHEV", program: "CYBER2", entity_type: "individual" },
  { name: "LAZARUS GROUP", program: "DPRK3", entity_type: "entity", remarks: "DPRK cyber" },
  { name: "PARK JIN HYOK", program: "DPRK3", entity_type: "individual", remarks: "Lazarus hacker" },
  { name: "JON CHANG HYOK", program: "DPRK3", entity_type: "individual" },
  { name: "KIM IL", program: "DPRK3", entity_type: "individual" },
  // === Venezuela ===
  { name: "TARECK EL AISSAMI", program: "VENEZUELA", entity_type: "individual", remarks: "VP" },
  { name: "PDVSA", program: "VENEZUELA", entity_type: "entity", remarks: "State oil company" },
  { name: "CARLOS ERICKSON MALPICA", program: "VENEZUELA", entity_type: "individual" },
  { name: "ALEX VAMOS NAIN SAAB MORAN", program: "VENEZUELA", entity_type: "individual", remarks: "Colombian dealmaker" },
  { name: "SAMUEL LOPEZ", program: "VENEZUELA", entity_type: "individual" },
  // === Burma/Myanmar ===
  { name: "MIN AUNG HLAING", program: "BURMA", entity_type: "individual", remarks: "Myanmar junta leader" },
  { name: "SOE WIN", program: "BURMA", entity_type: "individual" },
  { name: "MYANMAR ECONOMIC CORPORATION", program: "BURMA", entity_type: "entity" },
  { name: "MYANMAR ECONOMIC HOLDINGS LIMITED", program: "BURMA", entity_type: "entity" },
  // === Libya ===
  { name: "MUAMMAR AL-QADHAFI", program: "LIBYA2", entity_type: "individual", remarks: "Libya (deceased)" },
  { name: "SAADI AL-QADHAFI", program: "LIBYA2", entity_type: "individual" },
  { name: "HANNIBAL MUAMMAR AL-QADHAFI", program: "LIBYA2", entity_type: "individual" },
  // === Sudan ===
  { name: "OMAR HASSAN AHMAD AL-BASHIR", program: "SUDAN", entity_type: "individual", remarks: "Sudan (former)" },
  { name: "ABDEL RAHMAN MOHAMMED AHMED", program: "SUDAN", entity_type: "individual" },
  // === Zimbabwe ===
  { name: "ROBERT MUGABE", program: "ZIMBABWE", entity_type: "individual", remarks: "Zimbabwe (former, deceased)" },
  { name: "GRACE MUGABE", program: "ZIMBABWE", entity_type: "individual" },
  // === South Sudan ===
  { name: "MICHAEL MAKUEI LUETH", program: "SSUDAN", entity_type: "individual" },
  { name: "PAUL MALONG AWAN", program: "SSUDAN", entity_type: "individual" },
  // === DRC (Congo) ===
  { name: "GABRIEL AMISI KUMBA", program: "DRC", entity_type: "individual", remarks: "Congo General" },
  { name: "JOHN NUMBI", program: "DRC", entity_type: "individual" },
  // === Mali / Central African Republic ===
  { name: "ASSIMI GOITA", program: "Mali", entity_type: "individual", remarks: "Mali junta" },
  { name: "MAHAMAT IDRIS DEBY", program: "DARFOUR", entity_type: "individual", remarks: "Chad" },
];

export const SDN_LIST_SIZE = SDN_SAMPLE.length;
