// Evidence Chain & Provenance System (Feature 25)
//
// Maintains complete, immutable, and auditable provenance for every finding,
// relationship, inference, and report generated by the platform.
//
// Every piece of intelligence is traceable back to its origin with enough detail
// to allow a reviewer to reconstruct how the conclusion was reached, what sources
// were used, when the evidence was collected, how it was normalized, and what
// confidence was assigned at each stage of processing.
//
// 10 provenance attribute groups:
//   1. Collector — subsystem, method, execution context, version
//   2. Tool — exact tool, version, config, mode, limitations
//   3. Timestamp — collected, source-observed, ingested, normalized, scored
//   4. Query — exact query, params, investigation context, normalized form
//   5. Source URL — canonical URL, multiple refs, source type, canonicalization
//   6. Raw response — original payload, hash, size, truncation, omission reason
//   7. Normalized data — structured representation, transformation steps, field mappings
//   8. Confidence — score, rationale, raw/normalized/inferred confidence, propagation
//   9. Relationships — derived entities/relationships, corroboration, contradictions
//  10. Audit metadata — actor, access context, processing status, integrity, compliance
//
// Lifecycle stages: collection → validation → normalization → deduplication →
//   entity_resolution → correlation → scoring → synthesis → reporting →
//   re_scoring → historical_comparison → audit_review

import { db } from "@/lib/db";
import { createHash } from "crypto";
import type { SourceResult, NormalizedFinding, DetectionResult } from "./types";
import { getReliabilityTier, type ReliabilityTier } from "./confidence-engine";
import { safeJsonStringArray, safeJsonObject } from "./safe-json";

// ============================================================================
// DOMAIN TYPES
// ============================================================================

export type ProvenanceEventType =
  | "collection"
  | "validation"
  | "normalization"
  | "deduplication"
  | "entity_resolution"
  | "correlation"
  | "scoring"
  | "synthesis"
  | "reporting"
  | "enrichment"
  | "re_scoring"
  | "correction"
  | "historical_comparison";

export type CollectionMethod =
  | "crawler" | "api_client" | "parser" | "enrichment_service"
  | "manual_import" | "ai_extraction" | "webhook";

export type ToolMode = "sync" | "async" | "batch" | "streaming";

export type SourceType = "primary" | "secondary" | "mirror" | "archive" | "cached";

export type ActorType = "system" | "agent" | "user" | "api";

export type ProcessingStatus = "active" | "deprecated" | "redacted" | "deleted";

export interface ProvenanceEvent {
  id: string;
  investigationId: string;
  evidenceId: string;
  parentEventId?: string;
  eventType: ProvenanceEventType;
  eventTime: string;

  // Collector
  collectorName: string;
  collectionMethod: CollectionMethod;
  executionContext: Record<string, string>;
  collectorVersion: string;

  // Tool
  toolName: string;
  toolVersion: string;
  toolConfig: Record<string, unknown>;
  toolMode: ToolMode;
  toolLimitations: string;

  // Timestamp
  collectedAt: string;
  sourceObservedAt?: string;
  ingestedAt: string;
  normalizedAt?: string;
  scoredAt?: string;

  // Query
  queryString: string;
  queryParams: Record<string, unknown>;
  investigationContext: string;
  queryNormalized: string;

  // Source URL
  sourceUrl: string;
  sourceUrls: string[];
  sourceType: SourceType;
  canonicalization: string;

  // Raw response
  rawPayload: string;
  rawHash: string;
  rawSize: number;
  rawTruncated: boolean;
  rawOmissionReason: string;

  // Normalized data
  normalizedData: Record<string, unknown>;
  transformationSteps: string[];
  fieldMappings: Record<string, string>;
  normalizationVersion: string;

  // Confidence
  confidence: number;
  confidenceRationale: string;
  rawConfidence: number;
  normalizedConfidence: number;
  confidencePropagation: Record<string, unknown>;

  // Relationships
  derivedEntities: string[];
  derivedRelationships: string[];
  corroboratingEvidence: string[];
  contradictingEvidence: string[];

  // Audit metadata
  actorId: string;
  actorType: ActorType;
  accessContext: Record<string, unknown>;
  processingStatus: ProcessingStatus;
  retentionPolicy: string;
  integrityHash: string;
  retryCount: number;
  errorState: string;
  latencyMs: number;
  pipelineStage: string;

  createdAt: string;
}

export interface ProvenanceChain {
  evidenceId: string;
  events: ProvenanceEvent[];
  totalEvents: number;
  collectionEvents: number;
  normalizationEvents: number;
  scoringEvents: number;
  synthesisEvents: number;
  reportingEvents: number;
  earliestEvent: string;
  latestEvent: string;
  sourceChain: { sourceUrl: string; sourceType: SourceType; collectedAt: string; collector: string }[];
  confidenceHistory: { timestamp: string; confidence: number; rationale: string; eventType: string }[];
  derivedFrom: string[]; // parent evidence IDs
  derivedInto: string[]; // child evidence IDs
}

export interface ProvenanceStats {
  totalEvents: number;
  eventsByType: Record<string, number>;
  eventsByCollector: Record<string, number>;
  eventsByTool: Record<string, number>;
  uniqueEvidenceIds: number;
  uniqueSourceUrls: number;
  avgConfidence: number;
  lowConfidenceCount: number;
  highConfidenceCount: number;
  errorCount: number;
  truncatedRawCount: number;
  timeline: { timestamp: string; eventType: string; count: number }[];
}

export interface ProvenanceQuery {
  investigationId?: string;
  evidenceId?: string;
  eventType?: ProvenanceEventType;
  collectorName?: string;
  toolName?: string;
  sourceUrl?: string;
  minConfidence?: number;
  maxConfidence?: number;
  startTime?: string;
  endTime?: string;
  processingStatus?: ProcessingStatus;
  limit?: number;
  offset?: number;
}

export interface ProvenanceReport {
  investigationId: string;
  totalEvents: number;
  uniqueEvidenceIds: number;
  stats: ProvenanceStats;
  recentEvents: ProvenanceEvent[];
  evidenceChains: { evidenceId: string; eventCount: number; latestEventType: string; latestConfidence: number }[];
  generatedAt: string;
}

// ============================================================================
// PROVENANCE RECORDER — immutable event creation
// ============================================================================

/**
 * Record a provenance event. This is the core function — all provenance
 * recording flows through here. Events are immutable once created.
 */
export async function recordProvenanceEvent(
  event: Omit<ProvenanceEvent, "id" | "createdAt" | "integrityHash">
): Promise<ProvenanceEvent> {
  const id = `prov_${randomId()}`;
  const now = new Date().toISOString();
  const integrityHash = computeIntegrityHash({ ...event, id, createdAt: now });

  const fullEvent: ProvenanceEvent = {
    ...event,
    id,
    createdAt: now,
    integrityHash,
  };

  try {
    await db.provenanceEvent.create({
      data: {
        id: fullEvent.id,
        investigationId: fullEvent.investigationId,
        evidenceId: fullEvent.evidenceId,
        parentEventId: fullEvent.parentEventId || null,
        eventType: fullEvent.eventType,
        eventTime: new Date(fullEvent.eventTime),

        collectorName: fullEvent.collectorName,
        collectionMethod: fullEvent.collectionMethod,
        executionContext: JSON.stringify(fullEvent.executionContext),
        collectorVersion: fullEvent.collectorVersion,

        toolName: fullEvent.toolName,
        toolVersion: fullEvent.toolVersion,
        toolConfig: JSON.stringify(fullEvent.toolConfig),
        toolMode: fullEvent.toolMode,
        toolLimitations: fullEvent.toolLimitations,

        collectedAt: new Date(fullEvent.collectedAt),
        sourceObservedAt: fullEvent.sourceObservedAt ? new Date(fullEvent.sourceObservedAt) : null,
        ingestedAt: new Date(fullEvent.ingestedAt),
        normalizedAt: fullEvent.normalizedAt ? new Date(fullEvent.normalizedAt) : null,
        scoredAt: fullEvent.scoredAt ? new Date(fullEvent.scoredAt) : null,

        queryString: fullEvent.queryString,
        queryParams: JSON.stringify(fullEvent.queryParams),
        investigationContext: fullEvent.investigationContext,
        queryNormalized: fullEvent.queryNormalized,

        sourceUrl: fullEvent.sourceUrl,
        sourceUrls: JSON.stringify(fullEvent.sourceUrls),
        sourceType: fullEvent.sourceType,
        canonicalization: fullEvent.canonicalization,

        rawPayload: fullEvent.rawPayload,
        rawHash: fullEvent.rawHash,
        rawSize: fullEvent.rawSize,
        rawTruncated: fullEvent.rawTruncated,
        rawOmissionReason: fullEvent.rawOmissionReason,

        normalizedData: JSON.stringify(fullEvent.normalizedData),
        transformationSteps: JSON.stringify(fullEvent.transformationSteps),
        fieldMappings: JSON.stringify(fullEvent.fieldMappings),
        normalizationVersion: fullEvent.normalizationVersion,

        confidence: fullEvent.confidence,
        confidenceRationale: fullEvent.confidenceRationale,
        rawConfidence: fullEvent.rawConfidence,
        normalizedConfidence: fullEvent.normalizedConfidence,
        confidencePropagation: JSON.stringify(fullEvent.confidencePropagation),

        derivedEntities: JSON.stringify(fullEvent.derivedEntities),
        derivedRelationships: JSON.stringify(fullEvent.derivedRelationships),
        corroboratingEvidence: JSON.stringify(fullEvent.corroboratingEvidence),
        contradictingEvidence: JSON.stringify(fullEvent.contradictingEvidence),

        actorId: fullEvent.actorId,
        actorType: fullEvent.actorType,
        accessContext: JSON.stringify(fullEvent.accessContext),
        processingStatus: fullEvent.processingStatus,
        retentionPolicy: fullEvent.retentionPolicy,
        integrityHash: fullEvent.integrityHash,
        retryCount: fullEvent.retryCount,
        errorState: fullEvent.errorState,
        latencyMs: fullEvent.latencyMs,
        pipelineStage: fullEvent.pipelineStage,

        createdAt: new Date(now),
      },
    });
  } catch (e) {
    console.error("[provenance] record failed", e instanceof Error ? e.message : String(e));
  }

  return fullEvent;
}

// ============================================================================
// Specialized recording functions for each lifecycle stage
// ============================================================================

/**
 * Record evidence collection from a source.
 */
export async function recordCollection(
  investigationId: string,
  evidenceId: string,
  source: string,
  sourceLabel: string,
  finding: NormalizedFinding,
  detection: DetectionResult,
  latencyMs: number,
  pipelineStage: string
): Promise<ProvenanceEvent> {
  const now = new Date().toISOString();
  const tier = getReliabilityTier(source);
  const rawPayload = finding.data.slice(0, 2000); // cap at 2KB
  const rawHash = computeHash(finding.data);
  const rawTruncated = finding.data.length > 2000;

  return recordProvenanceEvent({
    investigationId,
    evidenceId,
    eventType: "collection",
    eventTime: now,

    collectorName: `source-runner:${source}`,
    collectionMethod: "api_client",
    executionContext: {
      investigationId,
      target: detection.sanitized,
      inputType: detection.inputType,
    },
    collectorVersion: "1.0.0",

    toolName: sourceLabel,
    toolVersion: "unknown",
    toolConfig: { source, target: detection.sanitized },
    toolMode: "sync",
    toolLimitations: tier <= 2 ? "Low-credibility source — verify with higher-tier sources" : "",

    collectedAt: finding.timestamp,
    sourceObservedAt: finding.timestamp,
    ingestedAt: now,

    queryString: `query_${source}("${detection.sanitized}")`,
    queryParams: { target: detection.sanitized, inputType: detection.inputType },
    investigationContext: `Investigation of ${detection.sanitized} (${detection.inputType})`,
    queryNormalized: `${source}:${detection.sanitized.toLowerCase()}`,

    sourceUrl: finding.source_url,
    sourceUrls: [finding.source_url],
    sourceType: tier >= 4 ? "primary" : tier >= 3 ? "primary" : "secondary",
    canonicalization: "",

    rawPayload,
    rawHash,
    rawSize: finding.data.length,
    rawTruncated,
    rawOmissionReason: rawTruncated ? "Raw payload truncated to 2KB for storage" : "",

    normalizedData: {
      data: finding.data,
      source_url: finding.source_url,
      confidence: finding.confidence,
      timestamp: finding.timestamp,
      extra: finding.extra || {},
    },
    transformationSteps: ["raw_extraction", "field_mapping", "confidence_assignment"],
    fieldMappings: { raw_text: "data", url: "source_url", score: "confidence", time: "timestamp" },
    normalizationVersion: "1.0.0",

    confidence: finding.confidence,
    confidenceRationale: `Source tier ${tier} (${getSourceTierLabel(tier)}). Base confidence: ${finding.confidence}.`,
    rawConfidence: finding.confidence,
    normalizedConfidence: finding.confidence,
    confidencePropagation: { source: "raw_observation", method: "direct" },

    derivedEntities: [],
    derivedRelationships: [],
    corroboratingEvidence: [],
    contradictingEvidence: [],

    actorId: "system:pipeline",
    actorType: "system",
    accessContext: { investigationId },
    processingStatus: "active",
    retentionPolicy: "24h TTL",
    retryCount: 0,
    errorState: "",
    latencyMs,
    pipelineStage,
  });
}

/**
 * Record normalization of a finding.
 */
export async function recordNormalization(
  investigationId: string,
  evidenceId: string,
  parentEventId: string,
  normalizedData: Record<string, unknown>,
  transformationSteps: string[],
  fieldMappings: Record<string, string>
): Promise<ProvenanceEvent> {
  const now = new Date().toISOString();
  return recordProvenanceEvent({
    investigationId,
    evidenceId,
    parentEventId,
    eventType: "normalization",
    eventTime: now,

    collectorName: "normalizer",
    collectionMethod: "parser",
    executionContext: { investigationId },
    collectorVersion: "1.0.0",

    toolName: "normalizer",
    toolVersion: "1.0.0",
    toolConfig: {},
    toolMode: "sync",
    toolLimitations: "",

    collectedAt: now,
    ingestedAt: now,
    normalizedAt: now,

    queryString: "",
    queryParams: {},
    investigationContext: "",
    queryNormalized: "",

    sourceUrl: "",
    sourceUrls: [],
    sourceType: "primary",
    canonicalization: "",

    rawPayload: "",
    rawHash: "",
    rawSize: 0,
    rawTruncated: false,
    rawOmissionReason: "Normalization event — no raw payload",

    normalizedData,
    transformationSteps,
    fieldMappings,
    normalizationVersion: "1.0.0",

    confidence: 0.8,
    confidenceRationale: "Normalization preserves source confidence with minor processing penalty.",
    rawConfidence: 0.8,
    normalizedConfidence: 0.8,
    confidencePropagation: { source: "parent_event", method: "inherit_with_penalty" },

    derivedEntities: [],
    derivedRelationships: [],
    corroboratingEvidence: [],
    contradictingEvidence: [],

    actorId: "system:normalizer",
    actorType: "system",
    accessContext: { investigationId },
    processingStatus: "active",
    retentionPolicy: "24h TTL",
    retryCount: 0,
    errorState: "",
    latencyMs: 0,
    pipelineStage: "normalize",
  });
}

/**
 * Record scoring/confidence assignment.
 */
export async function recordScoring(
  investigationId: string,
  evidenceId: string,
  parentEventId: string,
  confidence: number,
  rationale: string,
  pipelineStage: string
): Promise<ProvenanceEvent> {
  const now = new Date().toISOString();
  return recordProvenanceEvent({
    investigationId,
    evidenceId,
    parentEventId,
    eventType: "scoring",
    eventTime: now,

    collectorName: "confidence-engine",
    collectionMethod: "enrichment_service",
    executionContext: { investigationId },
    collectorVersion: "1.0.0",

    toolName: "confidence-engine",
    toolVersion: "1.0.0",
    toolConfig: {},
    toolMode: "sync",
    toolLimitations: "",

    collectedAt: now,
    ingestedAt: now,
    scoredAt: now,

    queryString: "",
    queryParams: {},
    investigationContext: "",
    queryNormalized: "",

    sourceUrl: "",
    sourceUrls: [],
    sourceType: "primary",
    canonicalization: "",

    rawPayload: "",
    rawHash: "",
    rawSize: 0,
    rawTruncated: false,
    rawOmissionReason: "Scoring event — no raw payload",

    normalizedData: { confidence, rationale },
    transformationSteps: ["source_tier_lookup", "recency_check", "corroboration_check", "confidence_calculation"],
    fieldMappings: {},
    normalizationVersion: "1.0.0",

    confidence,
    confidenceRationale: rationale,
    rawConfidence: confidence,
    normalizedConfidence: confidence,
    confidencePropagation: { source: "scoring_engine", method: "weighted_average" },

    derivedEntities: [],
    derivedRelationships: [],
    corroboratingEvidence: [],
    contradictingEvidence: [],

    actorId: "system:confidence-engine",
    actorType: "system",
    accessContext: { investigationId },
    processingStatus: "active",
    retentionPolicy: "24h TTL",
    retryCount: 0,
    errorState: "",
    latencyMs: 0,
    pipelineStage,
  });
}

/**
 * Record AI synthesis of findings into report.
 */
export async function recordSynthesis(
  investigationId: string,
  evidenceId: string,
  parentEventIds: string[],
  synthesisOutput: Record<string, unknown>,
  confidence: number,
  rationale: string
): Promise<ProvenanceEvent> {
  const now = new Date().toISOString();
  return recordProvenanceEvent({
    investigationId,
    evidenceId,
    parentEventId: parentEventIds[0], // link to first parent
    eventType: "synthesis",
    eventTime: now,

    collectorName: "ai-client:synthesizeReport",
    collectionMethod: "ai_extraction",
    executionContext: { investigationId, parentCount: String(parentEventIds.length) },
    collectorVersion: "1.0.0",

    toolName: "z-ai-web-dev-sdk:chat.completions",
    toolVersion: "latest",
    toolConfig: { thinking: "disabled", temperature: "low" },
    toolMode: "async",
    toolLimitations: "AI synthesis may introduce interpretation — verify against source evidence",

    collectedAt: now,
    ingestedAt: now,

    queryString: `synthesize(${parentEventIds.length} findings)`,
    queryParams: { parentEventIds },
    investigationContext: `Synthesis of ${parentEventIds.length} evidence items for investigation ${investigationId}`,
    queryNormalized: `synthesis:${investigationId}`,

    sourceUrl: "",
    sourceUrls: [],
    sourceType: "secondary",
    canonicalization: "",

    rawPayload: JSON.stringify(synthesisOutput).slice(0, 2000),
    rawHash: computeHash(JSON.stringify(synthesisOutput)),
    rawSize: JSON.stringify(synthesisOutput).length,
    rawTruncated: JSON.stringify(synthesisOutput).length > 2000,
    rawOmissionReason: "",

    normalizedData: synthesisOutput,
    transformationSteps: ["evidence_aggregation", "ai_synthesis", "json_parsing", "field_mapping"],
    fieldMappings: {},
    normalizationVersion: "1.0.0",

    confidence,
    confidenceRationale: rationale,
    rawConfidence: confidence,
    normalizedConfidence: confidence,
    confidencePropagation: { source: "ai_synthesis", method: "weighted_average_of_parents", parentCount: parentEventIds.length },

    derivedEntities: [],
    derivedRelationships: [],
    corroboratingEvidence: parentEventIds,
    contradictingEvidence: [],

    actorId: "system:ai-client",
    actorType: "system",
    accessContext: { investigationId },
    processingStatus: "active",
    retentionPolicy: "24h TTL",
    retryCount: 0,
    errorState: "",
    latencyMs: 0,
    pipelineStage: "synthesize",
  });
}

/**
 * Record report generation.
 */
export async function recordReporting(
  investigationId: string,
  evidenceId: string,
  parentEventIds: string[],
  reportSection: string,
  reportContent: string,
  confidence: number
): Promise<ProvenanceEvent> {
  const now = new Date().toISOString();
  return recordProvenanceEvent({
    investigationId,
    evidenceId,
    parentEventId: parentEventIds[0],
    eventType: "reporting",
    eventTime: now,

    collectorName: "pipeline:reportBuilder",
    collectionMethod: "parser",
    executionContext: { investigationId, reportSection },
    collectorVersion: "1.0.0",

    toolName: "pipeline",
    toolVersion: "1.0.0",
    toolConfig: {},
    toolMode: "sync",
    toolLimitations: "",

    collectedAt: now,
    ingestedAt: now,

    queryString: `report_section(${reportSection})`,
    queryParams: { reportSection, parentCount: parentEventIds.length },
    investigationContext: `Report section '${reportSection}' for investigation ${investigationId}`,
    queryNormalized: `report:${investigationId}:${reportSection}`,

    sourceUrl: "",
    sourceUrls: [],
    sourceType: "secondary",
    canonicalization: "",

    rawPayload: reportContent.slice(0, 2000),
    rawHash: computeHash(reportContent),
    rawSize: reportContent.length,
    rawTruncated: reportContent.length > 2000,
    rawOmissionReason: "",

    normalizedData: { reportSection, content: reportContent.slice(0, 500) },
    transformationSteps: ["evidence_selection", "report_formatting", "attribution_check"],
    fieldMappings: {},
    normalizationVersion: "1.0.0",

    confidence,
    confidenceRationale: `Report section '${reportSection}' derived from ${parentEventIds.length} evidence items.`,
    rawConfidence: confidence,
    normalizedConfidence: confidence,
    confidencePropagation: { source: "report_builder", method: "inherit_from_synthesis" },

    derivedEntities: [],
    derivedRelationships: [],
    corroboratingEvidence: parentEventIds,
    contradictingEvidence: [],

    actorId: "system:pipeline",
    actorType: "system",
    accessContext: { investigationId },
    processingStatus: "active",
    retentionPolicy: "24h TTL",
    retryCount: 0,
    errorState: "",
    latencyMs: 0,
    pipelineStage: "format",
  });
}

// ============================================================================
// PROVENANCE QUERY ENGINE
// ============================================================================

/**
 * Query provenance events with filters.
 */
export async function queryProvenanceEvents(query: ProvenanceQuery): Promise<ProvenanceEvent[]> {
  const where: Record<string, unknown> = {};
  if (query.investigationId) where.investigationId = query.investigationId;
  if (query.evidenceId) where.evidenceId = query.evidenceId;
  if (query.eventType) where.eventType = query.eventType;
  if (query.collectorName) where.collectorName = { contains: query.collectorName };
  if (query.toolName) where.toolName = { contains: query.toolName };
  if (query.sourceUrl) where.sourceUrl = { contains: query.sourceUrl };
  if (query.processingStatus) where.processingStatus = query.processingStatus;
  if (query.minConfidence !== undefined || query.maxConfidence !== undefined) {
    where.confidence = {};
    if (query.minConfidence !== undefined) (where.confidence as { gte?: number }).gte = query.minConfidence;
    if (query.maxConfidence !== undefined) (where.confidence as { lte?: number }).lte = query.maxConfidence;
  }
  if (query.startTime || query.endTime) {
    where.collectedAt = {};
    if (query.startTime) (where.collectedAt as { gte?: Date }).gte = new Date(query.startTime);
    if (query.endTime) (where.collectedAt as { lte?: Date }).lte = new Date(query.endTime);
  }

  const rows = await db.provenanceEvent.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: query.limit || 100,
    skip: query.offset || 0,
  });

  return rows.map(mapEvent);
}

/**
 * Get the full provenance chain for a specific evidence item.
 */
export async function getProvenanceChain(evidenceId: string): Promise<ProvenanceChain | null> {
  const events = await db.provenanceEvent.findMany({
    where: { evidenceId },
    orderBy: { eventTime: "asc" },
    take: 500,
  });

  if (events.length === 0) return null;

  const mappedEvents = events.map(mapEvent);

  const collectionEvents = mappedEvents.filter((e) => e.eventType === "collection").length;
  const normalizationEvents = mappedEvents.filter((e) => e.eventType === "normalization").length;
  const scoringEvents = mappedEvents.filter((e) => e.eventType === "scoring").length;
  const synthesisEvents = mappedEvents.filter((e) => e.eventType === "synthesis").length;
  const reportingEvents = mappedEvents.filter((e) => e.eventType === "reporting").length;

  const sourceChain = mappedEvents
    .filter((e) => e.sourceUrl)
    .map((e) => ({
      sourceUrl: e.sourceUrl,
      sourceType: e.sourceType,
      collectedAt: e.collectedAt,
      collector: e.collectorName,
    }));

  const confidenceHistory = mappedEvents
    .filter((e) => e.eventType === "scoring" || e.eventType === "collection" || e.eventType === "synthesis")
    .map((e) => ({
      timestamp: e.eventTime,
      confidence: e.confidence,
      rationale: e.confidenceRationale,
      eventType: e.eventType,
    }));

  const derivedFrom = [...new Set(mappedEvents.filter((e) => e.parentEventId).map((e) => e.parentEventId!))];

  // Find child evidence IDs (events where this evidenceId is a parent)
  const childEvents = await db.provenanceEvent.findMany({
    where: { parentEventId: { in: mappedEvents.map((e) => e.id) } },
    select: { evidenceId: true },
    distinct: ["evidenceId" as const],
    take: 50,
  });
  const derivedInto = childEvents.map((e) => e.evidenceId).filter((id) => id !== evidenceId);

  return {
    evidenceId,
    events: mappedEvents,
    totalEvents: mappedEvents.length,
    collectionEvents,
    normalizationEvents,
    scoringEvents,
    synthesisEvents,
    reportingEvents,
    earliestEvent: mappedEvents[0]?.eventTime || "",
    latestEvent: mappedEvents[mappedEvents.length - 1]?.eventTime || "",
    sourceChain,
    confidenceHistory,
    derivedFrom,
    derivedInto,
  };
}

/**
 * Get provenance stats for an investigation.
 */
export async function getProvenanceStats(investigationId: string): Promise<ProvenanceStats> {
  const events = await db.provenanceEvent.findMany({
    where: { investigationId },
    take: 10000,
  });

  if (events.length === 0) {
    return {
      totalEvents: 0,
      eventsByType: {},
      eventsByCollector: {},
      eventsByTool: {},
      uniqueEvidenceIds: 0,
      uniqueSourceUrls: 0,
      avgConfidence: 0,
      lowConfidenceCount: 0,
      highConfidenceCount: 0,
      errorCount: 0,
      truncatedRawCount: 0,
      timeline: [],
    };
  }

  const eventsByType: Record<string, number> = {};
  const eventsByCollector: Record<string, number> = {};
  const eventsByTool: Record<string, number> = {};
  const evidenceIds = new Set<string>();
  const sourceUrls = new Set<string>();
  let confSum = 0;
  let lowConf = 0;
  let highConf = 0;
  let errorCount = 0;
  let truncatedCount = 0;
  const timelineMap = new Map<string, { eventType: string; count: number }>();

  for (const e of events) {
    eventsByType[e.eventType] = (eventsByType[e.eventType] || 0) + 1;
    eventsByCollector[e.collectorName] = (eventsByCollector[e.collectorName] || 0) + 1;
    eventsByTool[e.toolName] = (eventsByTool[e.toolName] || 0) + 1;
    evidenceIds.add(e.evidenceId);
    if (e.sourceUrl) sourceUrls.add(e.sourceUrl);
    confSum += e.confidence;
    if (e.confidence < 0.4) lowConf++;
    if (e.confidence >= 0.7) highConf++;
    if (e.errorState) errorCount++;
    if (e.rawTruncated) truncatedCount++;

    const tsKey = new Date(e.eventTime).toISOString().slice(0, 19); // per-second
    const existing = timelineMap.get(tsKey);
    if (existing) {
      existing.count++;
    } else {
      timelineMap.set(tsKey, { eventType: e.eventType, count: 1 });
    }
  }

  const timeline = [...timelineMap.entries()]
    .map(([timestamp, val]) => ({ timestamp, eventType: val.eventType, count: val.count }))
    .sort((a, b) => a.timestamp.localeCompare(b.timestamp));

  return {
    totalEvents: events.length,
    eventsByType,
    eventsByCollector,
    eventsByTool,
    uniqueEvidenceIds: evidenceIds.size,
    uniqueSourceUrls: sourceUrls.size,
    avgConfidence: confSum / events.length,
    lowConfidenceCount: lowConf,
    highConfidenceCount: highConf,
    errorCount,
    truncatedRawCount: truncatedCount,
    timeline,
  };
}

/**
 * Get a full provenance report for an investigation.
 */
export async function getProvenanceReport(investigationId: string): Promise<ProvenanceReport> {
  const [stats, recentEvents, evidenceIds] = await Promise.all([
    getProvenanceStats(investigationId),
    db.provenanceEvent.findMany({
      where: { investigationId },
      orderBy: { createdAt: "desc" },
      take: 50,
    }),
    db.provenanceEvent.findMany({
      where: { investigationId },
      select: { evidenceId: true },
      distinct: ["evidenceId"],
      take: 200,
    }),
  ]);

  // Build evidence chain summaries
  const chainPromises = evidenceIds.slice(0, 50).map(async (e) => {
    const chain = await getProvenanceChain(e.evidenceId);
    if (!chain) return null;
    return {
      evidenceId: e.evidenceId,
      eventCount: chain.totalEvents,
      latestEventType: chain.events[chain.events.length - 1]?.eventType || "unknown",
      latestConfidence: chain.events[chain.events.length - 1]?.confidence || 0,
    };
  });
  const evidenceChains = (await Promise.all(chainPromises)).filter((c): c is NonNullable<typeof c> => c !== null);

  return {
    investigationId,
    totalEvents: stats.totalEvents,
    uniqueEvidenceIds: stats.uniqueEvidenceIds,
    stats,
    recentEvents: recentEvents.map(mapEvent),
    evidenceChains,
    generatedAt: new Date().toISOString(),
  };
}

// ============================================================================
// Mapping helpers
// ============================================================================

type ProvenanceRow = NonNullable<Awaited<ReturnType<typeof db.provenanceEvent.findUnique>>>;

function mapEvent(r: ProvenanceRow): ProvenanceEvent {
  return {
    id: r.id,
    investigationId: r.investigationId,
    evidenceId: r.evidenceId,
    parentEventId: r.parentEventId || undefined,
    eventType: r.eventType as ProvenanceEventType,
    eventTime: r.eventTime instanceof Date ? r.eventTime.toISOString() : String(r.eventTime),

    collectorName: r.collectorName,
    collectionMethod: r.collectionMethod as CollectionMethod,
    executionContext: safeJsonObject(r.executionContext) as Record<string, string>,
    collectorVersion: r.collectorVersion,

    toolName: r.toolName,
    toolVersion: r.toolVersion,
    toolConfig: safeJsonObject(r.toolConfig),
    toolMode: r.toolMode as ToolMode,
    toolLimitations: r.toolLimitations,

    collectedAt: r.collectedAt instanceof Date ? r.collectedAt.toISOString() : String(r.collectedAt),
    sourceObservedAt: r.sourceObservedAt instanceof Date ? r.sourceObservedAt.toISOString() : undefined,
    ingestedAt: r.ingestedAt instanceof Date ? r.ingestedAt.toISOString() : String(r.ingestedAt),
    normalizedAt: r.normalizedAt instanceof Date ? r.normalizedAt.toISOString() : undefined,
    scoredAt: r.scoredAt instanceof Date ? r.scoredAt.toISOString() : undefined,

    queryString: r.queryString,
    queryParams: safeJsonObject(r.queryParams),
    investigationContext: r.investigationContext,
    queryNormalized: r.queryNormalized,

    sourceUrl: r.sourceUrl,
    sourceUrls: safeJsonStringArray(r.sourceUrls),
    sourceType: r.sourceType as SourceType,
    canonicalization: r.canonicalization,

    rawPayload: r.rawPayload,
    rawHash: r.rawHash,
    rawSize: r.rawSize,
    rawTruncated: r.rawTruncated,
    rawOmissionReason: r.rawOmissionReason,

    normalizedData: safeJsonObject(r.normalizedData),
    transformationSteps: safeJsonStringArray(r.transformationSteps),
    fieldMappings: safeJsonObject(r.fieldMappings) as Record<string, string>,
    normalizationVersion: r.normalizationVersion,

    confidence: r.confidence,
    confidenceRationale: r.confidenceRationale,
    rawConfidence: r.rawConfidence,
    normalizedConfidence: r.normalizedConfidence,
    confidencePropagation: safeJsonObject(r.confidencePropagation),

    derivedEntities: safeJsonStringArray(r.derivedEntities),
    derivedRelationships: safeJsonStringArray(r.derivedRelationships),
    corroboratingEvidence: safeJsonStringArray(r.corroboratingEvidence),
    contradictingEvidence: safeJsonStringArray(r.contradictingEvidence),

    actorId: r.actorId,
    actorType: r.actorType as ActorType,
    accessContext: safeJsonObject(r.accessContext),
    processingStatus: r.processingStatus as ProcessingStatus,
    retentionPolicy: r.retentionPolicy,
    integrityHash: r.integrityHash,
    retryCount: r.retryCount,
    errorState: r.errorState,
    latencyMs: r.latencyMs,
    pipelineStage: r.pipelineStage,

    createdAt: r.createdAt instanceof Date ? r.createdAt.toISOString() : String(r.createdAt),
  };
}

// ============================================================================
// Utilities
// ============================================================================

function computeHash(data: string): string {
  return createHash("sha256").update(data).digest("hex").slice(0, 32);
}

function computeIntegrityHash(event: Record<string, unknown>): string {
  // Hash key fields for tamper detection
  const keyData = `${event.id}|${event.evidenceId}|${event.eventType}|${event.eventTime}|${event.confidence}|${event.sourceUrl}`;
  return computeHash(keyData);
}

function randomId(): string {
  return Math.random().toString(16).slice(2, 14) + Date.now().toString(16).slice(-4);
}

function getSourceTierLabel(tier: ReliabilityTier): string {
  const labels: Record<ReliabilityTier, string> = {
    5: "Authoritative",
    4: "Major threat intel",
    3: "Established data",
    2: "Community/aggregate",
    1: "Unverified",
  };
  return labels[tier];
}
